# /files/.github/workflows/dotnet.yml

# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# /files/.github/workflows/dotnet.yml

name: .NET

on:
  push:
    branches: [ "tunit" ]
  pull_request:
    branches: [ "tunit" ]

env:
  # Set the project directory name as an environment variable
  APP_NAME: Intrepion.HelloWorld

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{ env.APP_NAME }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Verify formatting
      run: dotnet format --verify-no-changes
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
